-- Create authors table to store Twitter author information
CREATE TABLE IF NOT EXISTS authors (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  handle VARCHAR(255) NOT NULL UNIQUE,
  display_name VARCHAR(255),
  bio TEXT,
  followers_count INTEGER DEFAULT 0,
  following_count INTEGER DEFAULT 0,
  tweet_count INTEGER DEFAULT 0,
  verified BOOLEAN DEFAULT FALSE,
  profile_image_url TEXT,
  banner_image_url TEXT,
  location VARCHAR(255),
  website_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  last_synced_at TIMESTAMP WITH TIME ZONE
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_authors_handle ON authors(handle);
CREATE INDEX IF NOT EXISTS idx_authors_created_at ON authors(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_authors_followers_count ON authors(followers_count DESC);

-- Create function to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION update_authors_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger to automatically update updated_at
CREATE TRIGGER update_authors_updated_at_trigger
  BEFORE UPDATE ON authors
  FOR EACH ROW
  EXECUTE FUNCTION update_authors_updated_at();

-- Insert the provided Twitter handles
INSERT INTO authors (handle) VALUES
('confugen'),
('MasonCanoe'),
('_brizal'),
('TrustlessState'),
('DeRonin_'),
('info_insightful'),
('theblessnetwork'),
('cysic_xyz'),
('AvantisFdn'),
('danielesesta'),
('JRossTreacher'),
('balajis'),
('realyanxin'),
('alphatrends'),
('nmtd8'),
('DayZ'),
('lucas_faster'),
('hotpot_dao'),
('defiignas'),
('spicyofc'),
('oviswang'),
('zun2025'),
('maverick23NFT'),
('off_thetarget'),
('Glenn_Diesen'),
('invariant_labs'),
('raoulgmi'),
('Igra_Labs'),
('lzminsky'),
('etherfi_VC'),
('degentradinglsd'),
('0x_scientist'),
('jeff__opinion'),
('SerrDavee'),
('reka_eth'),
('Ga__ke'),
('adamfdf_'),
('Hyperwavefi'),
('yekiM_o'),
('ihat'),
('Louround_'),
('celticmatheus'),
('yuyue_chris'),
('kuigas'),
('mobyagent'),
('zenea'),
('playoffthegrid'),
('xybrainz'),
('JiraiyaReal'),
('rexstjohn'),
('splinter0n'),
('SecRollins'),
('airn_619'),
('hebi555'),
('renckorzay'),
('klok_app'),
('allocateur'),
('nine_defi'),
('0xngmi'),
('aslan_web3'),
('KayTheDoc'),
('0xgumshoe'),
('yoheinakajima'),
('2lambro'),
('Covalent_HQ'),
('Emperor_coinsol'),
('beast_ico'),
('_FORAB'),
('0x_ultra'),
('zed_champions'),
('Jonathan_K_Cook'),
('peacefuldecay'),
('RubiksWeb3hub'),
('brave_raf'),
('scattering_io'),
('jakewittman'),
('dude_its_ritik'),
('liminalmoney'),
('Rugcheckxyz'),
('VersanAljarrah'),
('iamcoachcrypto'),
('crypthoem'),
('xdevelopers'),
('sadd_asd77675'),
('hashdag'),
('Cheshire_Cap'),
('DanBurmawy'),
('playsomo'),
('ArciumHQ'),
('fourvork'),
('0xasrequired'),
('StarPlatinumSOL'),
('goodalexander'),
('JohnLeFevre'),
('paretocredit'),
('KemiBadenoch'),
('Tiza4ThePeople'),
('bcs_bbt'),
('Ulydev'),
('Kyzer'),
('memeking_888'),
('1CryptoMama'),
('punk9277'),
('heyjxck_'),
('farmrick_hl'),
('minhxdynasty'),
('j0hnwang'),
('L0STE_'),
('GedaliahBlum'),
('MiyaHedge'),
('merchantmoe_xyz'),
('katexbt'),
('Defi_Scribbler'),
('jillrgunter'),
('hyperbloomxyz'),
('connorking_'),
('0xmadscientist'),
('OxTochi'),
('miraFND'),
('BankQuote_DAG'),
('aizenberg55'),
('AndreCronjeTech'),
('deronin_'),
('skate'),
('ThirdTimeIan'),
('RelayProtocol'),
('StalkHQ'),
('Luyaoyuan1'),
('CowellCrypto'),
('capradavis'),
('Enrique_GomezM'),
('btc563'),
('tokifinance'),
('corsica267'),
('MemeMarketFun'),
('tintsion'),
('brian_armstrong'),
('wagmigently'),
('taydotfun'),
('jermywkh'),
('tj_research01'),
('PrudentSammy'),
('TrumpWarRoom'),
('MarianneNFTs'),
('0xSunNFT'),
('0x_todd'),
('BasedMikeLee'),
('cryptofishx'),
('vohvohh'),
('Gradient_HQ'),
('imtomcurry'),
('roger9949'),
('ferbsol'),
('udiwertheimer'),
('choffstein'),
('heavendex'),
('theagnft'),
('buidlpad'),
('benbalamb'),
('munchPRMR'),
('ghitis'),
('alvin0617'),
('stable'),
('zeebuofficial'),
('MoonbeamNetwork'),
('oran_ge'),
('CryptoEights'),
('invest_answers'),
('Pi_Squared_Pi2'),
('citrea_xyz'),
('SpaceIDProtocol'),
('pharos_network'),
('SpekterAgency'),
('rickawsb'),
('PortaltoBitcoin'),
('SuhailKakar'),
('Infinit_Labs'),
('LLP_Le_Vrai'),
('nihaovand'),
('OpenverseGlobal'),
('boundless_xyz'),
('arndxt_xo'),
('CherylWroteIt'),
('mercy_okx'),
('Dashpay'),
('jussy_world'),
('getbeluga'),
('cryptocishanjia'),
('kklumiad'),
('solayer_labs'),
('DeepSafe_AI'),
('0xVeryBigOrange'),
('mattdotfi'),
('EmanAbio'),
('DegenApe99'),
('HoloworldAI'),
('getmoni_io'),
('jengelmayer'),
('0xbrans'),
('fuel_network'),
('Novastro_xyz'),
('GordoLeyes'),
('OlimpioCrypto'),
('tetsuoai'),
('zama_fhe'),
('crypto_rand'),
('glc_research'),
('fipcrypto'),
('stargatefinance'),
('AITECHio'),
('spencerguard'),
('S4mmyEth'),
('jsuarez5341'),
('nootropicsdao_'),
('mafiagame'),
('Mira_Network'),
('defi0xjeff'),
('Ethereum_OS'),
('aashatwt'),
('stablewatchhq'),
('thecryptoskanda'),
('0xjaehaerys'),
('FinanzasArgy'),
('cmdefi'),
('leonabboud_'),
('Habbo'),
('pixonchain'),
('FirstDescendant'),
('diogenescasares'),
('alpha_pls'),
('Breaking911'),
('0xbroze'),
('X'),
('MorphLayer'),
('RNCResearch'),
('hmalviya9'),
('fourpillarsfp'),
('virtuals_io'),
('trondao'),
('ifixhearts'),
('goatrollup'),
('BioProtocol'),
('0x_xifeng'),
('Bybit_Official'),
('chilla_ct'),
('EkoLovesYou'),
('amuse'),
('chaintrust0103'),
('officer_cia'),
('A_PoppOffiziell'),
('yzilabs'),
('threesigmaxyz'),
('maid_crypto'),
('Phyrex_Ni'),
('niallharbison'),
('jiamigoucn'),
('Adhwan'),
('RicardoBSalinas'),
('blocmatesdotcom'),
('daijapan'),
('openmind_agi'),
('bethesdastudios'),
('liu_web3'),
('fdanglehan56893'),
('SimonLevyMx'),
('SunriseLayer'),
('howie_serious'),
('bclaobai'),
('clarincom'),
('castle_labs'),
('BitBenderBrink'),
('DexCheck_io'),
('agintender'),
('VALORANTBrasil'),
('mia_okx'),
('Teslarati'),
('biteyecn'),
('richterry123'),
('hytopiagg'),
('Cobratate'),
('SlayStupidity'),
('techflowpost'),
('lianyanshe'),
('arletecaetana'),
('techAU'),
('Official_NODO'),
('wallet'),
('marvellousdefi_'),
('LuigiGiliberti2'),
('inside_il_intel'),
('ellatjonas'),
('harmonixfi'),
('TMtheOG'),
('edison0xyz'),
('SylvesterSolid'),
('0xkocha'),
('FabianoSolana'),
('kolyposts'),
('Tiger_Research_'),
('Kairos_Res'),
('0xRory'),
('Baheet_'),
('Jackhaldorsson')
ON CONFLICT (handle) DO NOTHING;