-- Migration 036: Rebuild daily_summary table with new schema
-- New schema: id, date, summary_en, summary_zh, summary_created_at

-- Drop old table
DROP TABLE IF EXISTS daily_summary CASCADE;

-- Create new table with simplified schema
CREATE TABLE daily_summary (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  date DATE NOT NULL UNIQUE,
  summary_en TEXT NOT NULL,
  summary_zh TEXT NOT NULL,
  summary_created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes
CREATE INDEX idx_daily_summary_date ON daily_summary(date);
CREATE INDEX idx_daily_summary_created_at ON daily_summary(summary_created_at DESC);

-- Enable Row Level Security
ALTER TABLE daily_summary ENABLE ROW LEVEL SECURITY;

-- Allow public read access
CREATE POLICY "Allow public read access to daily summaries" ON daily_summary
  FOR SELECT USING (true);

-- Only allow service role to insert/update
CREATE POLICY "Allow service role to manage daily summaries" ON daily_summary
  FOR ALL USING (auth.role() = 'service_role');

-- Add comment
COMMENT ON TABLE daily_summary IS 'Daily article summaries generated by DeepSeek AI - past 24h articles summarized into structured reports';
COMMENT ON COLUMN daily_summary.summary_en IS 'English summary of past 24 hours articles';
COMMENT ON COLUMN daily_summary.summary_zh IS 'Chinese translation of the daily summary';
COMMENT ON COLUMN daily_summary.summary_created_at IS 'When the summary was generated';
